name: my_games
description: "Aplicativo para gerenciar sua coleção de jogos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  http: ^1.1.2
  uuid: ^4.3.3
  file_picker: ^5.5.0  # Usando uma versão mais estável
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  sqflite_common_ffi_web: ^0.4.2
  sqflite_common_ffi: ^2.3.2
  flutter_typeahead: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 